### ISSUE TITLE
TypeError: Cannot read property 'spotify' of undefined

### ISSUE THREAD

**Issue by jaesmail** [katydecorah/spotify-to-jekyll#4]
Hi! Thanks so much for making this -- I'm super excited to use it!

Running into a problem when running the script: 

```
TypeError: Cannot read property 'spotify' of undefined
    at /Users/jihadesmail/Desktop/homepage/spotify-to-jekyll-master/index.js:48:31
    at new Promise (<anonymous>)
    at module.exports.formatTracks (/Users/jihadesmail/Desktop/homepage/spotify-to-jekyll-master/index.js:41:10)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any ideas?

**Comment by katydecorah** [comment]
Hey @jaesmail! I just pushed some updates and better error handling. Want to try again and let me know how it goes?

**Comment by jaesmail** [comment]
Hi @katydecorah! Appreciate your work on this. Downloaded the new folder, and got this error when installing:

```
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/spotify-to-jekyll
npm ERR! code ENOENT
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/spotify-to-jekyll
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/spotify-to-jekyll'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

**Comment by katydecorah** [comment]
@jaesmail Hmm, I think this is related to your local environment. The best thing I can recommend is trying to clone this repo again or making sure you pulled down the latest from `main` and following the install instructions again.

**Comment by katydecorah** [comment]
@jaesmail I decided to publish this to npm! You can install now via `npm install spotify-to-jekyll` see README.md for more details.
